### ISSUE TITLE
enhancements

### ISSUE THREAD

**Issue by Sispheor** [corus87/gpio-neuron#1]
[is_parameter_ok ](https://github.com/corus87/gpio-neuron/blob/master/gpio.py#L53)should test that the user set a list of integer or a single integer. 
```python
                 try:
                    parameter = int(parameter)
                except ValueError:
                    raise InvalidParameterException("[Gpio] %s is not a valid integer" % parameter)
```

The [open ](https://github.com/corus87/gpio-neuron/blob/master/gpio.py#L40)function should be replaced by the python 3 ready function with the "[with statement](https://stackoverflow.com/questions/9282967/how-to-open-a-file-using-the-open-with-statement)"

[Output parameters](https://github.com/corus87/gpio-neuron/blob/master/gpio.py#L48) are not documented.

The fact that the value is [celsius](https://github.com/corus87/gpio-neuron/blob/master/gpio.py#L46) and not fahrenheit should be documented too. 
Proposing a boolean like "return_fahrenheit" which would be set to false by default could be cool. If true, the script return the value in fahrenheit.

**Comment by corus87** [comment]
Thanks for the suggestions, I made the changes you proposed and also add a debug logger. 
What do you think?

**Comment by Sispheor** [comment]
Hi! Looks better. Great job.

I'm not sure if the program will not fail if the user provide a list of integer instead of a single integer [here](https://github.com/corus87/gpio-neuron/blob/master/gpio.py#L68).

**Comment by corus87** [comment]
Hi, thank you!  
Yes you are right, it fails... Im just trying to fix it but I have trouble to check if it is a list or integer. I trying [this](https://stackoverflow.com/questions/922774/check-if-input-is-a-list-tuple-of-strings-or-a-single-string) right now.

**Comment by Sispheor** [comment]
[Here is an example](https://github.com/kalliope-project/kalliope/blob/feature/hooks/kalliope/core/HookManager.py#L67)

If it's list, you add a `for each` with the test `int(value)`

**Comment by corus87** [comment]
Thank you that was helpful!  
I pushed a fix for it.

Btw. While trying out to solve I had of course a lot of exceptions. But the interessting part ist, after each "Execution skipped" I had to restart Kalliope, same behaviour like our [bug ](https://github.com/kalliope-project/kalliope/issues/386) .

**Comment by Sispheor** [comment]
Very interesting. I'll check this then.

Thx for the update !

**Comment by Sispheor** [comment]
I found a last test.

The user must set at least one of the two list (HIGH or LOW).

**Comment by corus87** [comment]
Fixed and thanks for the tests ^^
